NazarDia/TaskTracker-front

- src/components/Header/Header.jsx
- src/components/Header/Header.module.css
> initial component

- src/components/PopUps/Theme/Theme.jsx
- src/hooks/useUserData.js
- src/redux/auth/selectors.js
> add theme and hook

- src/components/Card/Card.jsx
- src/components/Card/Card.module.css
- src/components/CardsList/CardsList.jsx
- src/components/CardsList/CardsList.module.css
- src/components/ColumnStatus/ColumnStatus.jsx
- src/components/ColumnStatus/ColumnStatus.module.css
- src/components/PopUps/Filters/Filters.jsx
- src/components/TaskColumn/TaskColumn.jsx
- src/components/TaskColumn/TaskColumn.module.css
- src/components/TaskColumnsList/TaskColumnsList.jsx
- src/components/TaskColumnsList/TaskColumnsList.module.css
Додала стартові компоненти, поки без логіки
> add initial components for Dashboard

- src/styles/global.css
Додала назви змінних для кольорів, також додала кольори для різних тем для подальшого використовування
> add vars for colors

- src/styles/global.css
- src/styles/styles.css
Виправила порядок імпортів, щоб підтягувались і змінні і шрифти
> fixed imports for flobal styles

- src/components/HeaderButton/HeaderButtton.jsx
- src/components/PopUps/EditProfile/EditProfile.jsx
- src/components/PopUps/EditProfile/EditProfile.module.css
- src/components/PopUps/Theme/Theme.jsx
- src/components/PopUps/Theme/Theme.module.css
- src/components/ThemeSelect/ThemeSelect.jsx
- src/components/ThemeSelect/ThemeSelect.module.css
- src/components/UserInfo/UserInfo.jsx
- src/components/UserInfo/UserInfo.module.css
- src/redux/auth/operations.js
> add edit profile and selecttheme

- src/components/ColumnStatus/ColumnStatus.jsx
- src/components/ColumnStatus/ColumnStatus.module.css
- src/components/HeaderDashboard/HeaderDashboard.jsx
- src/components/HeaderDashboard/HeaderDashboard.module.css
- src/components/MainDashboard/MainDashboard.jsx
- src/components/MainDashboard/MainDashboard.module.css
- src/components/PopUps/AddColumn/AddColumn.jsx
- src/components/ScreensPage/ScreensPage.jsx
- src/components/ScreensPage/ScreensPage.module.css
- src/components/StartBoard/StartBoard.jsx
- src/components/StartBoard/StartBoard.module.css
- src/components/TaskColumn/TaskColumn.jsx
- src/components/TaskColumnsList/TaskColumnsList.jsx
- src/redux/columns/columnsSlice.js
- src/redux/columns/operations.js
- src/redux/store.js
Додала всі компоненти для колонок, lдодала запити на бек, додала редакс операції та слайс для колонок, залишилось селектори, в стор додала редюсер для колонок
> Adding start logic for columns

- src/components/BoardList/BoardList.jsx
- src/components/HeaderDashboard/HeaderDashboard.jsx
- src/components/HeaderDashboard/HeaderDashboard.module.css
- src/components/MainDashboard/MainDashboard.jsx
- src/components/ScreensPage/ScreensPage.jsx
- src/components/TaskColumnsList/TaskColumnsList.jsx
- src/redux/boards/boardSlice.js
- src/redux/boards/operations.js
Додала відображення борди, якщо вона є, її заголовка та колонок
> add bvasic logic for bords

- src/Schemas/schema.js
- src/components/BoardList/BoardList.jsx
- src/components/LoginForm/LoginForm.jsx
- src/components/RegisterForm/RegisterForm.jsx
Додала yup схеми у файл схем, підключила їх до сторінки логіну та реєстрації
> Add Schemas for login and Register  to schemas.js

- src/components/GeneralModal/GeneralModal.jsx
- src/components/GeneralModal/GeneralModal.module.css
- src/components/SideBarCreateBoard/SideBarCreateBoard.jsx
- src/images/sprite/sprite-icon.svg
Also added a modal window to create a new board
> Created General Modal

- src/components/Card/Card.jsx
- src/components/Card/Card.module.css
- src/components/PopUps/CardButton/CardButton.module.css
- src/components/PopUps/EditCard/EditCard.jsx
- src/components/TaskColumn/TaskColumn.jsx
- src/redux/cards/cardSlice.js
- src/redux/cards/operations.js
- src/styles/global.css
Додала логіку на відкриття модалок для відкриття при редагуванні та додаванні карточок, додала в глобальні стилі колір ховеру на кнопку
> adding logic for Add Card, edit card, delete card

- src/components/Card/Card.jsx
- src/components/PopUps/MoveCard/MoveCard.jsx
- src/components/TaskColumn/TaskColumn.jsx
Виправила, щоб не відмальовувались дві модалки при двох дженерал модал в одному компоненті
> Fixed 2 modals in the same time

- src/components/Card/Card.jsx
- src/components/HeaderDashboard/HeaderDashboard.jsx
- src/components/PopUps/MoveCard/MoveCard.jsx
- src/redux/cards/cardSlice.js
- src/redux/cards/operations.js
Додала код, щоб відкривався MoveCard, але ще треба доробити
> Add some logic for MoveCard

- src/components/ScreensPage/ScreensPage.jsx
додала логіку, щоб відображалась перша борда при логіні
> Set First Board as Default

- src/components/ScreensPage/ScreensPage.module.css
- src/components/ThemeSelect/ThemeSelect.jsx
- src/redux/auth/operations.js
- src/styles/global.css
Тепер зберігається тема при перезавантаженні та зберігається в кожному юзері своя тема
> Fixed Theme

- src/components/HeaderDashboard/HeaderDashboard.module.css
- src/components/MainDashboard/MainDashboard.jsx
- src/components/MainDashboard/MainDashboard.module.css
- src/components/ScreensPage/ScreensPage.jsx
- src/components/ScreensPage/ScreensPage.module.css
- src/components/StartBoard/StartBoard.module.css
- src/redux/boards/operations.js
- src/redux/boards/selectors.js
- src/styles/global.css
Додала зміну бг на борді, додала глобал змінні
> add Board Bg Change

- src/components/Card/Card.jsx
- src/components/Card/Card.module.css
- src/components/HeaderDashboard/HeaderDashboard.module.css
- src/components/ScreensPage/ScreensPage.module.css
Додала колір борда картки та підсвічування при ховері
> add Card border Color

- src/components/Card/Card.jsx
- src/components/Card/Card.module.css
- src/components/CardsList/CardsList.jsx
- src/components/PopUps/CardButton/CardButton.module.css
- src/components/TaskColumn/TaskColumn.jsx
- src/components/TaskColumn/TaskColumn.module.css
- src/styles/global.css
Додала ховери на rомпоненти колонок та на глобальний компонент кнопки, додала в глобальні стилі необхідні змінні
> Add Hovers to column's components and Btn

- src/components/PopUps/AddCard/AddCard.jsx
- src/components/PopUps/AddCard/AddCard.module.css
- src/components/PopUps/EditCard/EditCard.jsx
- src/components/PopUps/EditCard/EditCard.module.css
- src/components/PopUps/MoveCard/MoveCard.jsx
- src/redux/cards/operations.js
fix modal-Edit-card and remove currenCard in MoveCard
> fix modal-Edit-card

- src/components/CardsList/CardsList.jsx
- src/components/PopUps/Filters/Filters.jsx
- src/redux/columns/selectors.js
- src/redux/filters/selector.js
- src/redux/filters/slice.js
- src/redux/store.js
Reverts NazarDia/TaskTracker-front#105
> Revert "Filter mf"

- src/components/Card/Card.module.css
- src/components/CardsList/CardsList.jsx
- src/components/CardsList/CardsList.module.css
- src/components/ColumnStatus/ColumnStatus.module.css
- src/components/HeaderDashboard/HeaderDashboard.module.css
- src/components/MainDashboard/MainDashboard.module.css
- src/components/PopUps/CardButton/CardButton.module.css
- src/components/ScreensPage/ScreensPage.module.css
- src/components/StartBoard/StartBoard.jsx
- src/components/StartBoard/StartBoard.module.css
- src/components/TaskColumn/TaskColumn.module.css
- src/components/TaskColumnsList/TaskColumnsList.module.css
Додала стилі для відображення дошки на різних девайсах
> Origin dashboard

- src/components/Card/Card.jsx
- src/components/Card/Card.module.css
- src/components/CardsList/CardsList.module.css
- src/components/ColumnStatus/ColumnStatus.module.css
- src/components/MainDashboard/MainDashboard.module.css
- src/components/NeedHelp/NeedHelp.jsx
- src/components/NeedHelp/NeedHelp.module.css
- src/components/PopUps/MoveCard/MoveCard.module.css
- src/components/TaskColumn/TaskColumn.module.css
- src/components/TaskColumnsList/TaskColumnsList.module.css
- src/styles/global.css
styles changed for columns, add animation for need help
> styles changed for columns, add animation for need help

- src/components/TaskColumnsList/TaskColumnsList.jsx
- src/components/TaskColumnsList/TaskColumnsList.module.css
> Animation for cols
